
spring:
  datasource:
    url: jdbc:mysql://club-db:3306/clubdb?&allowPublicKeyRetrieval=true&useSSL=false


app:
  client:
    notification:
      url: http://club-notifications:8081/notifications

